### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by burf2000** [AlexTape/OpenMaka#1]
Hi there, I found this and looks awesome, however how do I get it up in running

I am trying to use Android Studio 1.3.  Is it worth me using Eclipse?

I open the project and set my ndk dir ndk.dir=/Users/burfies1/Library/Android/sdk/android-ndk-r10d

I get

In file included from src/main/jni/Main/commonCvFunctions.cpp:33:0:
src/main/jni/Main/commonCvFunctions.h:36:33: fatal error: opencv2/core/core.hpp: No such file or directory
 #include <opencv2/core/core.hpp>
                                 ^
compilation terminated.
make: **\* [build/obj/local/armeabi-v7a/objs/native_openmaka/Main/commonCvFunctions.o] Error 1
:app:ndkBuild FAILED
Error:Execution failed for task ':app:ndkBuild'.

> Process 'command '/Users/burfies1/Library/Android/sdk/android-ndk-r10d/ndk-build'' finished with non-zero exit value 2

**Comment by AlexTape** [comment]
Well.. I am using Android Studio 1.2. And yes, this Project is a Android Studio Project. BUT the project is actual in developing mode. Just follow the develope branch.. 

Maybe you should start with https://github.com/AlexTape/OpenCV-Marker-less-AR
OpenMaka is based on these sources. I try to get them running on Android during the next weeks.

The missing include can be fixed if you install opencv 2.4.11 for android from here: http://opencv.org/downloads.html

just download and unzip. after this you can mkdir a new folder inside of it (e.g. "build"). now cd build and cmake, make and make install. after this you got to set the pass inside the app/jni/android.mk for the opencv include. 

There are many howto´s on google.

well, android studio 1.3? really? thought 1.2 is the newest available instance..
---edit---
Awesome! http://tools.android.com/download/studio/canary/1-3-preview-2

**Comment by burf2000** [comment]
Thanks for getting back to me, I set this all up and when I run it the project is saying libgnustl_shared.so is missing, this may be because OpenCV3 does not have it but I will take a look

**Comment by AlexTape** [comment]
the libgnustl_shared.so is located in OpenMaka/app/src/main/jni/lib.

You are on windows? This project is atm not applicable to OpenCV3. Please use 2_4_11.

**Comment by burf2000** [comment]
Where do I get the nonfree from as 2.4.11 does not include it.  I am using a mac and the android version of OpenCV

**Comment by AlexTape** [comment]
they are located in OpenMaka/app/src/main/jni/lib -> libnonfree.so

**Comment by burf2000** [comment]
Oh I see your not building the libraries each time, how do I stop it trying to compile the libraries?  Mine is trying to build openCV each time?  

So if you download this and change nothing, it says the NDK path is missing, I set this and now its trying to build the libraries which is where files are missing.  Your build.gradle has lots of NDK stuff in it

**Comment by AlexTape** [comment]
you got to set sdk.dir and ndk.dir in OpenMaka/local.properties. After this configure pathes in app/build.gradle and set LOCAL_C_INCLUDES on line ~34 in app/src/main/jni/Android.mk.

**Comment by burf2000** [comment]
Thanks for helping, back to where I was.  

sdk.dir=/Users/burfies1/Library/Android/sdk
ndk.dir=/Users/burfies1/Library/Android/sdk/android-ndk-r10d

Using develope branch
LOCAL_C_INCLUDES:= /Users/burfies1/Downloads/OpenCV-android-sdk/sdk/native/jni/include/

Copied the .hpp files for nonfree etc so thats working

However it fails on 

06-09 13:34:25.832  11552-11552/de.alextape.openmaka E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.alextape.openmaka, PID: 11552
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found

I tried copying it in but it basically REBUILDS the jniLibs evertime

**Comment by burf2000** [comment]
Got it working, had to mod the Android.mk
How do I get the markerless stuff to work?

**Comment by AlexTape** [comment]
my turn! i think i will get it running in the next 1-2 weeks. I pushed some fixes today. atm you can recognize this images:
https://github.com/AlexTape/OpenCV-Marker-less-AR/tree/master/marker

Result would be:
de.alextape.openmaka I/NATIVE_MAIN﹕ Recognized id=1,probility=0.999990,matchnum=77, size=4
de.alextape.openmaka I/NATIVE_MAIN﹕ Recognized id=1,probility=0.999997,matchnum=83, size=4
de.alextape.openmaka I/NATIVE_MAIN﹕ Recognized id=1,probility=1.000000,matchnum=88, size=4

I got to port the whole opengl part in the next days. if you got any contribution e.g. copied .hpp headers or whatever, feel free to create pull requests.

kindly.

**Comment by burf2000** [comment]
Hey mate, I am happy to try and help as I know OpenGL pretty well (Java, not NDK).  Should I using Develope or Master?

**Comment by AlexTape** [comment]
awesome! Develope branch please :-)

**Comment by burf2000** [comment]
Want me to fork it, when I had it running it was only doing 2 frames and pausing a lot.  I am running a nexus 5?  thats probably the first thing I will look in to

**Comment by AlexTape** [comment]
I add an delay for the Feature Detection yesterday.. maybe you can check your cpu load?

**Comment by AlexTape** [comment]
How did you fix that missing libgnustl on Nexus5? I got no time to investigate cause i want to bring that thing forward for the S5 (g900f and g901f). But i got many devices here. also a Nexus5.. so if you can provide a running version i could maybe help you to get it running properly.

**Comment by burf2000** [comment]
Ok Dude, I will fork it and check it in

**Comment by burf2000** [comment]
Any chance you could tell me how to remove the delay, I done a commit on a fork on dev for you

**Comment by AlexTape** [comment]
I decided to do some tests on opencv3 because i got several trouble with basic functionalities. it feels much more faster now (10-14frames/sec). The delay is at line 168 in mainactivity

if (SystemClock.uptimeMillis() - time >= 1000) 

just change to 10000 or what..

if (SystemClock.uptimeMillis() - time >= 10000)

i will test your fork tomorrow on my nexus 5.

**Comment by burf2000** [comment]
Hey dude, sorry not been about, swamped at work.  Should I be using the v3 version now.  Hows it all going?

**Comment by AlexTape** [comment]
hey dude, i got several troubles with almost everything ;) first i decided to remove the opencv4android library and replace it with a lightweight camera implementation cause i dont need the opencv functions on java side. For this i have setup a new project https://github.com/AlexTape/AndroidCamera

Today i finished the prototype for my camera. So i will merge AndroidCamera with OpenMaka next days.

Right now i am on the opencv2 branch @openmaka.. i deleted the opencv3 branch because it was obsolete.

**Comment by burf2000** [comment]
Man your a busy chap.

So I need to get something working with markerless detection.  Should I use the original code, or something else

How do I add my own markers are they in YML?

**Comment by burf2000** [comment]
I have removed  if (VIEW_MODE_OBJECT_DETECTION || VIEW_MODE_TRACKING || VIEW_MODE_OPEN_GL) {
            //if (SystemClock.uptimeMillis() - time >= 1) {
                native_displayFunction(mRgbaAddr, mGrayAddr);
            //}
        }

but it still pauses badly for a second or so

**Comment by burf2000** [comment]
So I hacked about with the cpp files today and its still doing like 0.5fps even with removing all of the wait code.

**Comment by AlexTape** [comment]
Well, dont be too optimistic ;-) i will get it working in the next weeks.. maybe you want to play a bit with https://github.com/AlexTape/OpenCV-Marker-less-AR till i try to get it running on android.. As you can see in the actual Head Commit most of the JNI part is thrown away as i realized that the code was too creepy ;-)

**Comment by AlexTape** [comment]
furthermore i got really in trouble with Device Temperature and Energy Drain.. and low Fps like you noticed yourself.

**Comment by burf2000** [comment]
Hey mate, everything can be sorted now, this book http://techbus.safaribooksonline.com/book/programming/android/9781849695206/4dot-recognizing-and-tracking-images/ch04_html#X2ludGVybmFsX0h0bWxWaWV3P3htbGlkPTk3ODE4NDk2OTUyMDYlMkZjaDA0czA0X2h0bWwmcXVlcnk9 covers it all!

Chapter 4, and 5 is what you want

**Comment by AlexTape** [comment]
Hey, i know that book :) but thanks for the hint. But i dont want to realize it with java :)

**Comment by burf2000** [comment]
Oh will your way be faster, I am getting about 10fps at a low camera rate

**Comment by AlexTape** [comment]
10fps is good or bad? i will take a lool at it tomorrow.. but it feels like passing frames to the JNI Interface is faster with android4opencv Lib.. but who knows..

**Comment by AlexTape** [comment]
hey dude, checkout the experimental branch. detecting and tracking [miku](https://github.com/AlexTape/OpenMaka/blob/develope/app/src/main/assets/marker/miku.jpg) is working now. The code is veryyy dirty ;) i will go further next week..
